# 本地配置excel文件读取完整路径
[excel]
original_file_path=/Users/admin/PycharmProjects/agu/股票历史K线数据.xlsx
new_file_path=/Users/admin/PycharmProjects/agu/股票历史K线数据{current_time_stamp}.xlsx

[history_data]
primary_data_start_date=2026-01-01